// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicPlayerClone.Data;

#nullable disable

namespace MusicPlayerClone.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20251217163453_InitialDBContext")]
    partial class InitialDBContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MusicPlayerClone.Model.LikedSongscs", b =>
                {
                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<int>("songsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LikedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("userId", "songsId");

                    b.HasIndex("songsId");

                    b.ToTable("LikedSongs");
                });

            modelBuilder.Entity("MusicPlayerClone.Model.PlayListSongs", b =>
                {
                    b.Property<int>("playListId")
                        .HasColumnType("int");

                    b.Property<int>("songsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("playListId", "songsId");

                    b.HasIndex("songsId");

                    b.ToTable("playListSongs");
                });

            modelBuilder.Entity("MusicPlayerClone.Model.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("playLists");
                });

            modelBuilder.Entity("MusicPlayerClone.Model.Songs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("songs");
                });

            modelBuilder.Entity("MusicPlayerClone.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("uers");
                });

            modelBuilder.Entity("MusicPlayerClone.Model.LikedSongscs", b =>
                {
                    b.HasOne("MusicPlayerClone.Model.Songs", "songs")
                        .WithMany("likedBy")
                        .HasForeignKey("songsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicPlayerClone.Model.User", "user")
                        .WithMany("likesSongs")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("songs");

                    b.Navigation("user");
                });

            modelBuilder.Entity("MusicPlayerClone.Model.PlayListSongs", b =>
                {
                    b.HasOne("MusicPlayerClone.Model.Playlist", "playList")
                        .WithMany("playListSongs")
                        .HasForeignKey("songsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicPlayerClone.Model.Songs", "songs")
                        .WithMany("playListSongs")
                        .HasForeignKey("songsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("playList");

                    b.Navigation("songs");
                });

            modelBuilder.Entity("MusicPlayerClone.Model.Playlist", b =>
                {
                    b.HasOne("MusicPlayerClone.Model.User", "user")
                        .WithMany("playLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("MusicPlayerClone.Model.Playlist", b =>
                {
                    b.Navigation("playListSongs");
                });

            modelBuilder.Entity("MusicPlayerClone.Model.Songs", b =>
                {
                    b.Navigation("likedBy");

                    b.Navigation("playListSongs");
                });

            modelBuilder.Entity("MusicPlayerClone.Model.User", b =>
                {
                    b.Navigation("likesSongs");

                    b.Navigation("playLists");
                });
#pragma warning restore 612, 618
        }
    }
}
